User lookup by email
noobot/noobot pull request #103
Opened 2017-11-29 20:28 UTC by ddaron

In our project we match users based on their emails in slack enterprise grid and other external systems.
We needed functionality to find slack user id by email, so that we could message people directly based on their email address.

2017-11-29 20:49 UTC, Workshop2 requested changes
Thanks for the PR. Please see feedback

2017-11-29 20:49 UTC, Workshop2 commented on src/Noobot.Core/NoobotCore.cs
> +            var user = _connection.UserCache.Where(x => x.Value.Email != null).FirstOrDefault(x => x.Value.Email.Equals(email, StringComparison.OrdinalIgnoreCase));
This is a very long method, could it be broken up?

2017-11-29 20:49 UTC, Workshop2 commented on src/Noobot.Core/NoobotCore.cs
> +        public string GetUserIdForUserEmail(string email)
This is missing unit tests

2017-12-06 08:13 UTC, ddaron commented
Sure, will do

2017-12-19 11:34 UTC, Workshop2 commented on src/Noobot.Core/NoobotCore.cs
> +            _log.Info($"Id for user: {GetUserIdForUserEmail("zimny.jot@gmail.com")}");
Not sure this is meant to be there

2017-12-19 11:34 UTC, Workshop2 commented
Thanks for your hard work. I can clean up that last bit when I go on a computer

2017-12-19 11:35 UTC, ddaron commented on src/Noobot.Core/NoobotCore.cs
> +            _log.Info($"Id for user: {GetUserIdForUserEmail("zimny.jot@gmail.com")}");
Whoops, you're right

2017-12-28 17:50 UTC, merged

2017-12-28 18:03 UTC, Workshop2 commented
Released https://github.com/noobot/noobot/releases/tag/3.1.55